// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TeHagoLaFila.Models;

namespace TeHagoLaFila.Migrations
{
    [DbContext(typeof(TeHagoLaFilaContext))]
    [Migration("20180407044932_Updated")]
    partial class Updated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeHagoLaFila.Models.CategoriaEmpleado", b =>
                {
                    b.Property<int>("CategoriaEmpleadoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CategoriaEmpleadoID");

                    b.ToTable("CategoriaEmpleado");
                });

            modelBuilder.Entity("TeHagoLaFila.Models.CategoriaNegocio", b =>
                {
                    b.Property<int>("CategoriaNegocioID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CategoriaNegocioID");

                    b.ToTable("CategoriaNegocio");
                });

            modelBuilder.Entity("TeHagoLaFila.Models.Negocio", b =>
                {
                    b.Property<int>("NegocioID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Direccion")
                        .IsRequired();

                    b.Property<int>("IDCategoriaNegocioID");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("NegocioID");

                    b.HasIndex("IDCategoriaNegocioID");

                    b.ToTable("Negocio");
                });

            modelBuilder.Entity("TeHagoLaFila.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ConfirmarClave");

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<byte[]>("Image");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Telefono")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("TeHagoLaFila.Models.Negocio", b =>
                {
                    b.HasOne("TeHagoLaFila.Models.CategoriaNegocio", "ID")
                        .WithMany()
                        .HasForeignKey("IDCategoriaNegocioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
